spring:
  gateway:
    default-filters:
      # 令牌中继
      - TokenRelay=
      # 代理路径，代理至服务后会去除第一个路径的内容
      - StripPrefix=1
    routes:
      # 路由Id
      - id: faircloud-iam-service
        #代理服务器地址
        uri: lb://faircloud-iam-service
        #断言规则
        predicates:
          - Path=/iam/**